name: Update QA Rating

on:
  workflow_dispatch:        # manual trigger
  schedule:
    - cron: "0 * * * *"     # every hour

jobs:
  qa-rating-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install \
            gspread \
            oauth2client \
            gspread-dataframe \
            pandas \
            requests

      - name: Run QA rating update
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: python QA-rating-update.py
